# Generated by Django 2.1.2 on 2018-11-30 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('character_name', models.CharField(max_length=500)),
                ('picture_url', models.CharField(max_length=5000, null=True)),
            ],
            options={
                'db_table': 'crew',
            },
        ),
        migrations.CreateModel(
            name='CrewCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crew_category',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('synopsis', models.CharField(max_length=5000)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('genres', models.ManyToManyField(db_table='movie_has_genre', related_name='_movie_genres_+', to='core.Genre')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_category',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserHasWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_has_watchlist',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default_list', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.User')),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
        migrations.CreateModel(
            name='WatchlistHasMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed_at', models.DateTimeField()),
                ('added_by', models.ForeignKey(db_column='added_by', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.User')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Movie')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasMovies', to='core.Watchlist')),
            ],
            options={
                'db_table': 'watchlist_has_movie',
            },
        ),
        migrations.CreateModel(
            name='WatchlistPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'watchlist_permission',
            },
        ),
        migrations.AddField(
            model_name='userhaswatchlist',
            name='permission',
            field=models.ForeignKey(db_column='watchlist_permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.WatchlistPermission'),
        ),
        migrations.AddField(
            model_name='userhaswatchlist',
            name='shared_by',
            field=models.ForeignKey(db_column='shared_by', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.User'),
        ),
        migrations.AddField(
            model_name='userhaswatchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.User'),
        ),
        migrations.AddField(
            model_name='userhaswatchlist',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Watchlist'),
        ),
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(db_column='picture_category', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.PictureCategory'),
        ),
        migrations.AddField(
            model_name='picture',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.Movie'),
        ),
        migrations.AddField(
            model_name='crew',
            name='category',
            field=models.ForeignKey(db_column='crew_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CrewCategory'),
        ),
        migrations.AddField(
            model_name='crew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='core.Movie'),
        ),
    ]
